/**
 * Generated-file detection for symbol-disambiguation down-ranking.
 *
 * When a query like "Send" matches 17 symbols across protobuf scaffolding,
 * test mocks, and the hand-written implementation, the FTS ranker often
 * surfaces the generated stubs first because their names are identical
 * to the implementation's name (validated empirically on cosmos-sdk —
 * see project_go_multi_module_audit memory). Generated stubs frequently
 * have no body to trace from, so the agent ends up reading source anyway.
 *
 * This helper is a pure path-based classifier consulted at disambiguation
 * time (findSymbol / findAllSymbols / codegraph_search formatting), NOT
 * a hard filter — generated nodes are still in the graph and remain
 * reachable; they just rank LAST when there's a real implementation
 * with the same name.
 *
 * Scope: suffix patterns only. Most generated files follow the
 * `<basename>.<tool>.<ext>` convention (`.pb.go`, `_grpc.pb.go`,
 * `.g.dart`, `_pb2.py`), and that covers ~all of what we saw in the
 * Go audit. A future addition would be scanning for the canonical
 * `// Code generated by` header during extraction, for the rare files
 * that defy the suffix convention.
 */

const GENERATED_PATTERNS: ReadonlyArray<RegExp> = [
  // Go — protobuf / gRPC / pulsar
  /\.pb\.go$/,
  /\.pulsar\.go$/,
  /_grpc\.pb\.go$/,
  // Go — mockgen output. Default emits `mock_<src>.go`; many projects
  // (cosmos-sdk uses `expected_*_mocks.go`) rename to `*_mock.go` /
  // `*_mocks.go`. Matching either suffix catches both conventions
  // without false-positive risk on hand-written sources.
  /_mock\.go$/,
  /_mocks\.go$/,
  /^mock_[^/]+\.go$/,
  // TypeScript / JavaScript — common codegen suffix
  /\.generated\.[jt]sx?$/,
  // Python — protobuf
  /_pb2(_grpc)?\.py$/,
  // C++ — protobuf
  /\.pb\.(cc|h)$/,
  // Dart — build_runner / freezed
  /\.g\.dart$/,
  /\.freezed\.dart$/,
];

/**
 * Whether `filePath` looks like a tool-generated source file based on
 * its filename. Path-only — does not read content. The result is a
 * relevance hint for disambiguation, not a hard claim.
 */
export function isGeneratedFile(filePath: string): boolean {
  return GENERATED_PATTERNS.some((p) => p.test(filePath));
}
